### ISSUE TITLE
pre-index and access-config not loading properly after some time

### ISSUE THREAD

**Issue by Matzexxxxx** [whitewillem/PMSF#135] opened 2019-04-18 00:18 UTC
**Issue:**
When using an access-config and discord-login, the permissions to the logged in discord-user isnt working properly after some time ( maybe 5-15 minutes after closing and reopening the map)
For my case, the frontend is only showing the default config enabled options, but not the ones defined in the access-config (for the pokemon-menuoption for example).
Something is messing up with the session i guess, since the logged in user is still displayed in the navbar, but everything from the access-config isnt applied.
Also, the modt defined in the access-config is displayed when that error occurs. even if the modt is set to false in the access-config, but true in the normal configs.

**Reproduce that error:**
Setup a PMSF instance with a proper discord-login and an access-config.
disable modt in the access-config and enable it in the normal config.php
enable the pokemon menu (noPokemon = false) in the access-config and disable the pokemon menu by default config.php (noPokemon = true)
Log in on the map, close the browser - wait 10-15 minutes and reopen the map again. 

**PS:**
On that status, reloading the page again is resolving that problem. After the reload, everything is fine.
Did anyone else experienced this? its only with access-config and discord-login. Without the login-system there is no such an error

**Comment by Soda-City-PoGo** [comment] 2019-04-18 00:27
I experience the same issue, yes refreshing works to fix it. I thought it always had something to do with the anti-scraping stuff but i don't know.

**Comment by xxleevo** [comment] 2019-04-18 02:30
This also seems to happen after you reopen your browser. Time doesnt matter
If you only close the tab and open the map in a new one, its like a reload and fixing it. If you close the browser and reopen up the browser, the error is there again.

**Comment by gtkingz** [comment] 2019-04-18 08:59
I can confirm I have the same problem.

**Comment by ColdShadow80** [comment] 2019-04-18 09:07
Problem is not exclusive to Discord login. Have same problem in legacy (email) login.
Basicaly, after loggin in you need to refresh to get all menu data.

Example, if no login users have no acesso to "Active quests" menu and it is disable by default, the menu is hidden. After login in a profile that has acess, the menu still has the option hidden.

Only after a manual refresh are the setinngs fully aplied and the side menu refreshed to the proper acess-config settings.

**Comment by plinytheelder** [comment] 2019-04-18 15:44
This has been broken since the login system was merged into PMSF a year ago. It is currently the biggest bug plaguing our users and our inboxes from users who complain or don't understand why their access isn't working correctly.

**Comment by t00fan** [comment] 2019-05-08 18:17
This is a pretty big pain point for the users.  Creates lots of inquiry for access.  Would really appreciate a fix! Thank you.

**Comment by Gladiator10864** [comment] 2019-05-10 20:08
Please fix. I'll bake you cookies and ship if you do!!! This is the number one complaint I get from my users on the map as well.

**Comment by ColdShadow80** [comment] 2019-05-23 08:53
Problem seems solved with latest dev commits. Tested using MAD branch and RM database

**Comment by whitewillem** [comment] 2019-06-02 18:38
Will close this for now as its 'fixed' in develop branch.

**Closed by whitewillem** 2019-06-02 18:38 UTC

**Comment by DrKendall** [comment] 2019-09-16 09:08
Similar issue has arose after closing the browser. 
When the browser is closed after login, you're logged out when you revisit. Even if I revisit within 10s of closing.
